version: 1
disable_existing_loggers: True


formatters:
  default: 
    format: '[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d 
    - %(name)s:%(funcName)s: %(message)s'


handlers:
  default: 
    class: logging.FileHandler
    filename: Logging\log_files\logs.log
    encoding: utf-8
    mode: a
    level: DEBUG
    formatter: default


loggers:
  main:
    level: DEBUG
    handlers: [default]


root:
  formatter: default
  handlers: [default]
